### PR TITLE
set up natural keys in models with dependencies

### PR DESCRIPTION
**Pull request by paulapreuss**
With this feature, `dumpdata `and `loaddata` can now be done without specifying pks/natural keys (normally the names) can now be used to specify dependencies. This will eliminate issues and leave less room for error either when updating the db with new demandtimeseries or setting up the new db after flushing.

Data can also be dumped in this format by running
`python manage.py dumpdata cp_nigeria.consumergroup --natural-foreign --natural-primary --indent 2 > dump.json`
(or whatever table to be dumped). This makes for a more readable export, e.g. to save the data from the workshops.

### CODE REVIEW

**Comment by paulapreuss** [comment]
I did this in preparation for the import of new timeseries (updated machinery and places of worship). We can talk about the best approach for the database update (dump workshop data / flush timeseries and reload all of them or just upload / update the new ones - in this case we still have to be careful because some ts will have to be deleted either way). I will then get the fixture ready for whatever we do.

**Review by Bachibouzouk — COMMENTED** [review]
No migrations file?

**Comment by paulapreuss** [comment]
[demand_profiles_update.json](https://github.com/rl-institut/cp_nigeria_app/files/13449121/demand_profiles_update.json)


This file contains the new peoplesun demand profiles. This includes:

- Updated school profile
- New mosque and church profiles
- Updated machinery profiles (and here, sometimes one new profile replaces two old ones, apparently)

Since there was no machinery included in the pre-loaded communities it will only break the links to the school profiles which should be an easy fix. The machinery might have been used in the workshops, so there will likely be some links breaking in those projects. The way I see it, the best way to update the database would be to:

0. (dump the old consumergroup data with `python manage.py dumpdata cp_nigeria.consumergroup --natural-foreign --natural-primary --indent 2 > dump.json`)
1. Delete the DemandTimeseries with name = "Education_School" (outdated School profile)
2. Delete all DemandTimeseries with consumer_type = "Machinery" (all of these are outdated)
3. Load the new data into the database
4. Update the "Education_School" ConsumerGroups for the communities to link to the new "School" profile

Alternatively, we could update the school profile instead of creating a new one by specifying the pk for this profile when loading it.

**Comment by Bachibouzouk** [comment]
Timeseries for "School" is missing from the json file (it is "Education_School" I believe) and it prevents step 3


Deleting the timeseries in step 1 with "Public facility" ended up deleting a community and therefore more usergroups
(40, {'cp_nigeria.ConsumerGroup': 27, 'cp_nigeria.Options': 2, 'cp_nigeria.DemandTimeseries': 5,
      'projects.Timeseries': 5, 'cp_nigeria.Community': 1})
      
 This was probably because the Community would be wrongly have PV timeseries being another timeseries. If I delete the timeseries of Public facilities after being thought the 4 steps, I don't delete a community anymore :)

**Comment by paulapreuss** [comment]
> Timeseries for "School" is missing from the json file (it is "Education_School" I believe) and it prevents step 3
> 
> Deleting the timeseries in step 1 with "Public facility" ended up deleting a community and therefore more usergroups (40, {'cp_nigeria.ConsumerGroup': 27, 'cp_nigeria.Options': 2, 'cp_nigeria.DemandTimeseries': 5, 'projects.Timeseries': 5, 'cp_nigeria.Community': 1})
> 
> This was probably because the Community would be wrongly have PV timeseries being another timeseries. If I delete the timeseries of Public facilities after being thought the 4 steps, I don't delete a community anymore :)

Thanks for noticing! I realized there are two errors in my old comment/file: 
- I manually updated the Education_School name to just "School", but probably forgot to do it both in the child and parent objects. This should be updated and then work fine.
- I thought only school was in public facilities, but now realized that the health facilities are also in there (and the old mismatch with the PV timeseries then caused the community to delete). That means we need to delete only the school profile instead of all public facilities instead.

**Pull request merged**
