### PR TITLE
Feature/fate implementation

### PR DESCRIPTION
**Pull request by paulapreuss**
So far, the methods work for fetching the inputs from the database (i am working off of feature/demand-input-backend, so i can generate some consumergroups and then use that data). Needs to be rebased on #32 when it is merged.

The test methods work for changing the values in the FATE excel, extracting values, creating plotly graph and then putting those graphs inside a work doc. That means that the entire pipeline is functional (at least on my windows system). Feel free to play around and see if it also runs on yours. 

even if you don't have demand data in your db, simply creating a FATEHandler instance 

`instance = FATEHandler()`
`instance.graph_to_output_file()`

should manage to create the output graph and word doc from the data currently in the FATE file into the static folder

### CODE REVIEW

**Comment by paulapreuss** [comment]
Reevaluating formulas in excel doesn't work, need to find a solution

**Comment by paulapreuss** [comment]
But excel graphs and report download can be tested at "proj_id"/fate_outputs

**Comment by Bachibouzouk** [comment]
> Reevaluating formulas in excel doesn't work, need to find a solution

Some things I found on the subject

- https://xlsxwriter.readthedocs.io/faq.html

- https://stackoverflow.com/questions/58957012/how-to-get-libreoffice-headless-calc-calculate-to-save-new-values-from-uno
- https://python-ooo-dev-tools.readthedocs.io/en/latest/odev/part1/chapter02.html

**Comment by Bachibouzouk** [comment]
As the FATE tool calculation could be performed in python in #88 we don't need that anymore :)

**Pull request closed without merging**
